<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>RonCS</AssemblyName>
    <PackageId>RonCS</PackageId>
    <Version>0.0.1</Version>
    <Authors>RJ Reynolds</Authors>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Superpower" Version="3.2.1" />
  </ItemGroup>
</Project>
