<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>RonCS</AssemblyName>
    <PackageId>RonCS</PackageId>
    <Version>0.1.4</Version>
    <Authors>CriusNyx</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Superpower" Version="3.2.1" />
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
